# Generated by Django 5.1 on 2024-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
